#!/bin/bash

[ -d "tmp" ] && rm -rf tmp
#mkdir tmp && cd tmp && cmake .. -DCMAKE_INSTALL_PREFIX=~/ -DLOCALEDIR=${HOME}/.local/share/locale -DDEBUG=1
mkdir tmp && cd tmp && cmake .. -DCMAKE_INSTALL_PREFIX=~/ -DDEBUG=1
make VERBOSE=1
# make install

